# Generated by Django 5.2.5 on 2025-08-09 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=120)),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('waitlist_enabled', models.BooleanField(default=True)),
                ('is_team_event', models.BooleanField(default=False)),
                ('team_size_min', models.PositiveIntegerField(default=1)),
                ('team_size_max', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('team_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAITLIST', 'Waitlist')], default='CONFIRMED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'status'], name='events_regi_email_7c6b3e_idx')],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
